#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SDK="$ROOT/rexglue-sdk"
PORT="$ROOT/rexlego"
BUILD="$SDK/out/build/android-codegen-host"

if [[ $# -lt 1 || $# -gt 2 ]]; then
  cat >&2 <<'EOF'
Usage:
  android/generate-android-sources.sh /path/to/extracted/LEGO-Dimensions [Default.xex]

The extracted game must already contain the TU23 executable patch next to the
base XEX. For example:
  Default.xex
  Default.xexp

Nothing from the game is copied into Git. Codegen output stays under:
  rexlego/generated/
EOF
  exit 2
fi

GAME_ROOT="$(cd "$1" && pwd)"
XEX_NAME="\${2:-}"

if [[ -z "$XEX_NAME" ]]; then
  XEX_NAME="$(
    python3 - "$GAME_ROOT" <<'PY'
import os, sys
root=sys.argv[1]
matches=[n for n in os.listdir(root) if n.lower()=="default.xex"]
print(matches[0] if matches else "")
PY
  )"
fi

if [[ -z "$XEX_NAME" || ! -f "$GAME_ROOT/$XEX_NAME" ]]; then
  echo "Could not find Default.xex in: $GAME_ROOT" >&2
  exit 3
fi

XEX="$GAME_ROOT/$XEX_NAME"
XEXP="\${XEX}p"
if [[ ! -f "$XEXP" ]]; then
  cat >&2 <<EOF
TU23 executable patch is missing.

Expected the loader's sibling patch here:
  $XEXP

Put TU23's XEXP beside the base XEX before codegen. Android is built for TU23
and intentionally rejects an unpatched 0.0.0.3 image.
EOF
  exit 4
fi

echo "[1/4] Preparing the Android-capable ReXGlue source tree..."
"$ROOT/android/prepare-rexglue.sh"

if ! command -v cmake >/dev/null 2>&1; then
  echo "cmake is required to build the host codegen tool." >&2
  exit 5
fi
if ! command -v ninja >/dev/null 2>&1; then
  echo "ninja is required to build the host codegen tool." >&2
  exit 5
fi
if ! command -v clang++ >/dev/null 2>&1; then
  echo "clang++ 18 or newer is required to build ReXGlue." >&2
  exit 5
fi

echo "[2/4] Building the native ReXGlue codegen tool..."
cmake -S "$SDK" -B "$BUILD" -G Ninja \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_C_COMPILER=clang \
  -DCMAKE_CXX_COMPILER=clang++ \
  -DREXGLUE_BUILD_TOOLS=ON \
  -DREXGLUE_BUILD_TESTS=OFF \
  -DREXGLUE_ENABLE_TRACY=OFF \
  -DREXGLUE_ENABLE_FIDELITYFX=OFF \
  -DREXGLUE_ENABLE_DESKTOP_SDL_BACKENDS=OFF \
  -DREXGLUE_USE_VULKAN=ON

cmake --build "$BUILD" --target rexglue --parallel

REXGLUE="$BUILD/src/rexglue/rexglue"
if [[ ! -x "$REXGLUE" ]]; then
  REXGLUE="$(find "$BUILD" -type f -perm -111 \( -name rexglue -o -name rexglue.exe \) -print -quit)"
fi
if [[ -z "$REXGLUE" || ! -x "$REXGLUE" ]]; then
  echo "The rexglue codegen executable was not found after the build." >&2
  exit 6
fi

MANIFEST="$PORT/legodimensions_manifest.android.toml"
echo "[3/4] Writing Android codegen manifest..."
python3 - "$PORT" "$GAME_ROOT" "$XEX" "$MANIFEST" <<'PY'
import json, pathlib, sys
port=pathlib.Path(sys.argv[1]).resolve()
game=pathlib.Path(sys.argv[2]).resolve()
xex=pathlib.Path(sys.argv[3]).resolve()
manifest=pathlib.Path(sys.argv[4])
def q(p):
    return json.dumps(str(p))
manifest.write_text(
    "# Generated by android/generate-android-sources.sh\n"
    "# Local paths only; do not commit this file.\n\n"
    "[project]\n"
    'name = "legodimensions"\n'
    'sdk_version = "0.10.0"\n'
    f"game_root = {q(game)}\n\n"
    "[entrypoint]\n"
    f"file_path = {q(xex)}\n"
    'out_directory_path = "generated/default"\n'
    'includes = ["legodimensions_config.toml"]\n',
    encoding="utf-8",
)
print(manifest)
PY

echo "[4/4] Generating Android-compatible PPC -> C++ sources..."
(
  cd "$PORT"
  "$REXGLUE" codegen --pointer_table_scan --ignore-stamp "$(basename "$MANIFEST")"
)

PCH="$PORT/generated/default/legodimensions_pch.h"
SOURCES="$PORT/generated/default/sources.cmake"
if [[ ! -f "$PCH" || ! -f "$SOURCES" ]]; then
  echo "Codegen completed without the expected generated/default outputs." >&2
  exit 7
fi
if ! grep -q "g_guest_phys_host_offset" "$PCH" ||
   ! grep -q "REX_SYNC_FENCE" "$PCH"; then
  echo "Generated sources do not contain the Android ARM64 codegen markers." >&2
  exit 8
fi

echo
echo "Android-compatible generated sources are ready:"
echo "  $PORT/generated/default"
echo
echo "Next:"
echo "  $ROOT/android/build-android.sh debug"
